### ISSUE TITLE
simulation_duration comes from transmission_demo and not gi.json

### ISSUE THREAD

**Issue by Sv3tlana** [jonathanhhb/covid_app#9]
configStubJson initialized from gi.json.
Initialized Statics from gi.json.

these two lines make me think that Simulation_Duration from gi.json is loaded and used, but it is not. 
Took me a minute to figure that out.

**Comment by jonathanhhb** [comment]
ya, all unused params from gi.json should be removed before this is really "ready to wear".

**Comment by jonathanhhb** [comment]
Related to #2.

**Comment by jonathanhhb** [comment]
Fixed.
